### ISSUE TITLE
Adding more routes & organizing routes

### ISSUE THREAD

**Issue by demamoh** [irahardianto/service-pattern-go#2]
First of all great repository, very "clean" architecture. 

One of the questions I have is about adding more routes. Currently all your routes are in router.InitRouter. How would you manage having more routes like close to 50? Would you still keep everything in InitRouter?

The other question I have is about organizing routes. Would you organize your controller methods together in  a set function? Also, how would you?

**Comment by irahardianto** [comment]
Hi, I am sorry for the very late reply, I'll pay more attention for notification in the future.

Yes that is the idea, they will be listed down in the InitRouter. As for controller function separation, it is already neatly contained in each service container inject function. if you have any advice I welcome PR & advice to make the repo better.

**Comment by demamoh** [comment]
No problem. Thanks.
